# These are supported funding model platforms
custom: [PayPal](https://www.paypal.com/donate/?business=JN9YD94DHA87Y&no_recurring=0&item_name=Help+create+the+worlds+first+bibliography+of+maritime+search+%26+rescue.+Saving+lives+through+sharing+knowledge.+Thank+you.&currency_code=USD)
